SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE acompañante;
TRUNCATE TABLE audio;
TRUNCATE TABLE audioxcomparecencia;
-- TRUNCATE TABLE catalogocaso;
-- TRUNCATE TABLE catalogooficina;
-- TRUNCATE TABLE catalogopuesto;
-- TRUNCATE TABLE catalogoregion;
TRUNCATE TABLE comparecencia;
TRUNCATE TABLE gestionado;
TRUNCATE TABLE gestionante;
TRUNCATE TABLE inspector;
TRUNCATE TABLE inspectorxcomparecencia;
TRUNCATE TABLE persona;
TRUNCATE TABLE personajuridica;
TRUNCATE TABLE representante;
TRUNCATE TABLE testigo;
TRUNCATE TABLE usuario;
SET FOREIGN_KEY_CHECKS = 1;